### ISSUE TITLE
遇到2个小问题

### ISSUE THREAD

**Issue by Slevin-Wong** [molihuan/BilibiliCacheVideoMergePython#3]
①有部分视频导出不了，卡在复制这一步了，TEMP文件夹里没有东西，说明是没有复制成功
②导出成功后TEMP文件夹里的临时文件没有自动清理，相当于我导出1次就会产生2个视频文件

**Comment by molihuan** [comment]
> ①有部分视频导出不了，卡在复制这一步了，TEMP文件夹里没有东西，说明是没有复制成功
> ②导出成功后TEMP文件夹里的临时文件没有自动清理，相当于我导出1次就会产生2个视频文件

请提供系统简单信息和缓存文件，如果能够提供问题复现步骤那就更好了，1492906929@qq.com

**Comment by Slevin-Wong** [comment]
> > ①有部分视频导出不了，卡在复制这一步了，TEMP文件夹里没有东西，说明是没有复制成功
> > ②导出成功后TEMP文件夹里的临时文件没有自动清理，相当于我导出1次就会产生2个视频文件
> 
> 请提供系统简单信息和缓存文件，如果能够提供问题复现步骤那就更好了，[1492906929@qq.com](mailto:1492906929@qq.com)

Sorry，我才发现你后来的新版本，新版本暂时没有这个问题，打扰了
