### ISSUE TITLE
安卓版(miui14)非root设备无法授予data目录访问权限

### ISSUE THREAD

**Issue by tianyilover** [molihuan/BilibiliCacheVideoMergePython#4]
![1](https://github.com/molihuan/BilibiliCacheVideoMergePython/assets/115713335/4c5a21db-6b5f-4d44-a601-caf327d6df35)
开发者有办法解决嘛？还是说得自己想办法？

**Comment by molihuan** [comment]
> ![1](https://github.com/molihuan/BilibiliCacheVideoMergePython/assets/115713335/4c5a21db-6b5f-4d44-a601-caf327d6df35)
> 开发者有办法解决嘛？还是说得自己想办法？

连接电脑可以访问，在电脑导出缓存文件

**Comment by tianyilover** [comment]
太厉害了，大佬

**Comment by molihuan** [comment]
> 太厉害了，大佬

没有问题我就关闭这个issues了，也有手机版的，只不过兼容性不太好

**Comment by luis-arch** [comment]
您好，有没有可能通过shizuku给该android软件提权来解决这个问题呢
